language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
before_install:
  - export DJANGO_SETTINGS_MODULE=suit_redactor.tests.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test suit_redactor
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: pypy
      env: DJANGO=1.5
